title: Header

display:
  min-width: 320px

context:
  asset_path: '/assets/'
  include_path: 'components/header/'

  title: &basic_title
    text: Department of Web Standards
    href: &null_href javascript:void(0)

variants:

  - name: default
    label: Basic

    context:
      primary: &basic_nav
        - title: First section
          id: one
          links: &link_list
            - text: One link
              href: *null_href
            - text: Another link
              href: *null_href
            - text: Yet another link
              href: *null_href
        - title: Second section
          id: two
          links: *link_list
        - title: Third section
          id: three
          href: *null_href
        - title: Fourth section
          id: four
          links: *link_list

  - name: basic-mega
    label: Basic with megamenu
    context:
      primary: &mega_sections
        - title: First section
          id: first
          columns:
            - links: *link_list
            - links: *link_list
            - links: *link_list
            - links: *link_list
        - title: Second section
          id: second
          columns:
            - links: *link_list
            - links: *link_list
            - links: *link_list
        - title: Third section
          id: third
          links: *link_list
        - title: Fourth section
          id: fourth
          href: *null_href

  - name: extended
    label: Extended
    context:
      primary: *basic_nav
      secondary: &extended_nav
        links:
          - text: First link
            href: *null_href
          - text: Second link
            href: *null_href

  - name: extended-mega
    label: Extended with megamenu
    context:
      primary: *mega_sections
      secondary: *extended_nav
